### ISSUE TITLE
Totems and their essence

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-totem#3]
I'm not currently a user may not understand the essence or is that too silly thing, look, if I put for innocent totem, I can easily determine who slows down near him, that is, it is a check. Or Vice versa, the traitor puts and also can already be innocent to determine who is who, slows down a person or not. So what's the point then? Maybe we should remove the slow and then leave only acceleration?

**Comment by saibotk** [comment]
you cannot identify people just by checking if they are slowed down, i cannot get your point, also since this is the implementation of a feature used by the german YouTuber Dhalucard, we do not have the intention to redesign the feature or change it gameplaywise. This would happen in a new addon or additionally. The slow is applied to anybody who does not have a totem anymore, so when the Totemhunter removes many totems, one may identify a person, but he cannot really confirm the person, because you dont know which totem belongs to whom. And otherwise its intended to be like that. ;)

**Comment by TimGoll** [comment]
Additionally all totems (except traitor totems) can be removed. Since there is a jackal, no one can be confirmed. Additionally there is sprint and other items that change the speed.

Overall I'd say this is no problem.

**Comment by dok441** [comment]
We tested sprint totem and even on the standard greatly increases the speed and it is noticeable. On account of the fact that a totem only works on those who have, in fact, wrong, and traitors are the only traitors( acceleration), and totems innocent(acceleration), but innocent. And slowing down on the opposite team. I'm just saying it's easy to abuse, it's weird that no one thought of that.

**Comment by TimGoll** [comment]
It's the same with traitor testers or reading your role backwarts. There's always a way to get your role without roleplay. But this problem has never happened for us in Totem since we do not try to abuse systems

**Comment by dok441** [comment]
If everyone was like that, then everyone would live in Paradise.

**Comment by saibotk** [comment]
Just as i said, the gameplay wont be changed, since it is intended to be like that and people want it to be like that.
